# Site settings
title: Ardor Education
description: Ardor Education
baseurl: ''
url: https://www.ardoreducation.com
exclude: [vendor]
frontPage:
  title:
  summary:
  intro:

about:
  title:
  summary:

contactus:
  educators: >
    Do you want to be an advocate for improving math education? We’d love to talk to you. Please send us an <a href="mailto:contact@ardoreducation.com">email</a>
    so we can begin the conversation.

  support: >
    Please let us know how we can help you.
  investors: >
    Are you interested in investment opportunities with Ardor Education? We'd love to hear from you.
    <a href="https://gust.com/companies/ardor-education-inc">Visit Gust</a>
    to read our business plan and learn more about us.


curriculum:
  title: curriculum
  links: >
    <a
      href="https://itunes.apple.com/us/app/ardor-math/id953832689?ls=1&mt=8">
      <img class="app-store-badge" src="./../assets/images/logo/App_Store_Badge.svg">
    </a>
    <a
      href="https://play.google.com/store/apps/details?id=com.ardor.algebradojo">
      <img class="app-store-badge" src="./../assets/images/logo/play-store-badge.png">
    </a>
    <br>
    Download the free app. Learn more about
    <a
      href="https://support.google.com/chromebook/answer/7021273?hl=en">Android for Chromebooks.
    </a> Request or ask about a
    <a
      href="mailto:contact@ardoreducation.com?Subject=Request%Problem%Type" target="_top"
    >
     specific problem type.
    </a>
  grade7:
    - title: Number Line
      standards: 7.NS.A.1 | 7.NS.A.1.A | 7.NSA.A.1.C
      image: './../assets/images/curriculum/grade7/number-line.jpeg'
      description: >
        to use number lines for addition and subtraction.  Find distances between quantities. Combine opposite quantities to make 0.
        Combine quantities to make negatives. Add and subtract positive and negative integers. Use absolute value to find distances.
        Subtract rational numbers as the additive invers. p -  q = p + (-q).

    - title: Rational Numbers
      standards: 7.NS.A.1 | 7.NS.A.1.B
      image: './../assets/images/curriculum/grade7/integers.jpeg'
      description: >
        to multiply and divide positive and negative rational numbers.
        Use the order of operations to simplfy expressions that include both
        positive and negative integers.

    - title: Expressions
      standards: 7.EE.A.1
      image: './../assets/images/curriculum/grade7/expressions.jpeg'
      description: >
        apply properties of operations to add, subtract, factor and expand linear expresssions. Evaulate expressions by replacing variables.
        Simplify expressions, combine like terms, distribute and write sums as a product of two factors.

    - title: One Variable Equations
      standards: 7.EE.A.1
      image: './../assets/images/curriculum/grade7/one-variable-equations.jpeg'
      description: >
        to solve one step and two step one variable equations.
        Model equations using tiles.
        Use tiles to solve equations. Solve equations to find missing angles in triangles
        and parallelograms. Use distributive property to solve equations. Write and solve equations for real-life problems.

    - title: Area and Perimeter
      standards: 7.G.B.6
      image: './../assets/images/curriculum/grade7/area.png'
      description: >
        to solve problems involving area and perimeter of rectangles, triangles, quadralaterals, and mixed shapes.
        Solve for missing sides area and perimeter.

    - title: Volume and Surface Area
      standards: 7.G.B.6
      image: './../assets/images/curriculum/grade7/pyramid.jpeg'
      description: >
        to solve problems involving volume and surface area of pyramids, prisms, cubes and mixed three dimensional objects.

    - title: Fractions and Decimals
      standards: 7.NS.2.D
      image: './../assets/images/curriculum/grade7/fraction.jpeg'
      description: >
        to convert fractions to a decimals using long divsion. Understand when a decimal number
        terminates, repeats, or is irrational.

    - title: Percents
      standards: 7.RP.A.3
      image: './../assets/images/curriculum/grade7/percent.jpeg'
      description: >
        to solve percent problems. Problems involving part, whole or percents of numbers.
        Percent of increase and decrese. Simple interest, tax, discounts and percent of error.

  grade8:
    - title: One Variable Equations
      standards: 8.EE.C.7 | 8.EE.C.7.A |  8.EE.C.7.B
      image: './../assets/images/curriculum/grade7/one-variable-equations.jpeg'
      description: >
        to solve one step, two step and multiple step one variable equations. Identify
        equations with one solution, infinitely many solutions, or no solutions.
        Use algebra tiles to solve equations. Use distributive property to solve equations. Write and solve equations for real-life problems.

    - title: Angles
      standards: 8.G.A.5
      image: './../assets/images/curriculum/grade8/transversal.png'
      description: >
        to solve for missing angles in triangles parallelograms and transversals. Use
        facts about angle sum and exterior angles of triangles to solve problems. Know how to
        apply properties of coorisponding and supplemental angles to solve angle expression problems.

    - title: Exponents and Scientific Notation
      standards: 8.EE.A.4
      image: './../assets/images/curriculum/grade8/scientific-notation.jpeg'
      description: >
        to perform operations with numbers expressed in scientific notation. Simplify expressions
        with exponents.

    - title: Pythagorean Theorem
      standards: 8.G.B.7 | 8.G.B.6
      image: './../assets/images/curriculum/grade8/ladder.jpeg'
      description: >
        apply the Pythagorean Theorem to determine side lengths in right triangles.
        Solve real-world problems. Apply the Pythagorean Theorem to find the distnace between
        two points in a coordinate system.

    - title: Volume
      standards: 8.G.C.9
      image: './../assets/images/curriculum/grade8/ice-cream-cone.jpeg'
      description: >
        to solve volumes of cylinders, cones, and spheres. Solve volumes of mixed shapes
        such as ice-cream cones, pills, and pencils.

    - title: Transformations
      standards: 8.G.A.3
      image: './../assets/images/curriculum/grade8/rotation.jpeg'
      description: >
        to describe the effect of rotations, reflections, translations and dilations.
        Use transformation rules to perform transformations.

    - title: Slope Tables and Graphs
      standards: 8.EE.B.5 | 8.F.B.4
      image: './../assets/images/curriculum/grade8/slope.jpeg'
      description: >
        to determine the rate of change from graphs and tables. Identify the slope
        from graphs and tables as part of a linear model.

    - title: Slopes From Points
      standards: 8.F.B.4
      image: './../assets/images/curriculum/grade8/bamboo.jpeg'
      description: >
        to construct linear models. Use graphs and tables to make predictions.
        Solve real-world problems that compare the rate of change between two quantities.

    - title: Linear Equations
      standards: 8.F.B.4
      image: './../assets/images/curriculum/grade8/linear-equations.jpeg'
      description: >
        to write linear equations given points or table of values. Indentify slope,
        y-intercepts. Change between standard and y-intercept forms.

    - title: Linear Grahps
      standards: 8.F.B.4
      image: './../assets/images/curriculum/grade8/linear-graph.jpeg'
      description: >
        to write linear equations that describe graphs. Write equations that fit
        points. Identify points that create a linear relationship.

    - title: Linear Systems
      standards: 8.EE.C.8.B | 8.EE.C.8.C
      image: './../assets/images/curriculum/grade8/substitution.jpeg'
      description: >
        to solve linear systems algebraicly using the substitution method. Estimate solutions
        using graphs. Solve real-world problems modeled using linear systems.

  algebra:
    - title: One Variable Equations
      standards: HSA.SSE.A.1.A | HSA.REI.A.2
      image: './../assets/images/curriculum/grade7/one-variable-equations.jpeg'
      description: >
        to solve one step, two step and multiple step one variable equations. Identify
        equations with one solution, infinitely many solutions, or no solutions.
        Use tiles to model and interpret parts of an equation.
        Use algebra tiles to solve equations.  Use distributive property to solve equations. Write and solve equations for real-life problems.

    - title: Variables and Functions
      standards: HSA.SSE.A.1
      image: './../assets/images/curriculum/algebra/expressions.png'
      description: >
        to replace variables with values to simplify expressions. Use function notation.

    - title: Slope Tables and Graphs
      standards: HSA.CED.A.2
      image: './../assets/images/curriculum/grade8/slope.jpeg'
      description: >
        to determine the rate of change from graphs and tables. Identify the slope
        from graphs and tables as part of a linear model.

    - title: Slopes From Points
      standards: HSA.CED.A.2
      image: './../assets/images/curriculum/grade8/bamboo.jpeg'
      description: >
        to construct linear models. Use graphs and tables to make predictions.
        Solve real-world problems that compare the rate of change between two quantities.

    - title: Linear Equations
      standards: HSA.CED.A.2
      image: './../assets/images/curriculum/grade8/linear-equations.jpeg'
      description: >
        to write linear equations given points or table of values. Indentify slope,
        y-intercepts. Change between standard and y-intercept forms.

    - title: Linear Grahps
      standards: HSA.CED.A.2
      image: './../assets/images/curriculum/grade8/linear-graph.jpeg'
      description: >
        to write linear equations that describe graphs. Write equations that fit
        points. Identify points that create a linear relationship.

    - title: Linear Systems Substitution
      standards: HSA.REI.C.6
      image: './../assets/images/curriculum/grade8/substitution.jpeg'
      description: >
        to solve linear systems algebraicly using the substitution method. Estimate solutions
        using graphs. Solve real-world problems modeled using linear systems.

    - title: Linear Systems
      standards: HSA.REI.C.6
      image: './../assets/images/curriculum/algebra/elimination.jpeg'
      description: >
        to solve linear systems algebraicly using the a variety of methods including
        substitution, elimination by addition and subtraction and elimination using multiplication.
        Solve real-world problems modeled using linear systems.

    - title: Polynomials
      standards: HSA.SSE.B.3 | HSA.SSE.B.3.A
      image: './../assets/images/curriculum/algebra/factor.jpeg'
      description: >
        to factor quadratic expressions. Product equivalent forms of quadratic expressions.
        Multiply binomial and trinomial expressions.

    - title: Quadratics
      standards: HSA.REI.B.4.B
      image: './../assets/images/curriculum/algebra/solve-quadratic-square-root.jpeg'
      description: >
        to solve quadratic equations by taking the squre root. Solve quadratics by factoring and complete the square methods.

    - title: Quadratic Graphs
      standards: HSA.APR.B.3 | HSA.REI.B.4.B
      image: './../assets/images/curriculum/algebra/axis.jpeg'
      description: >
        to identify and solve for the axis of symmetry, vertex, and x-intercepts from a quadratic equation and graph.
        Model quadratics using standard form, factored form and vertex form.

    - title: Quadratic Formula and Methods
      standards: HSA.APR.B.3 | HSA.REI.B.4.B
      image: './../assets/images/curriculum/algebra/quadratic-word-problem.jpeg'
      description: >
        to use the quadratic formula and complete the square methods to solve quadratics.
        Solve real-world problems. Solve for vertex, axis of symmetrty and x-intercepts.

  geometry:
    - title: Volume
      standards: HSG.GMD.A.3
      image: './../assets/images/curriculum/grade8/cone.png'
      description: >
        to solve volumes of pyramids, prisms, cylinders, cones, and spheres. Solve volumes of mixed shapes
        such as ice-cream cones, pills, and pencils.


team:
  title:
  summary:
  profiles:
    - name: Ardor Education, Inc
      title: ''
      image: 'assets/images/logo/ardor-logo A.png'
      summary: >
        <p>
        We are a small team located in Portland OR. We are passionate about education
        and the power of technology to improve it. Are you a teacher or an advocate
        for improving math education? We’d love to talk to you.
        Please send us an <a href="mailto:contact@ardoreducation.com">email</a>
        so we can begin the conversation.
        </p>
    - name: Matt Thornton
      title: Founder & CEO
      image: 'assets/images/profile/matthew.jpg'
      summary: >
        <p>
        I have taught math and science in middle and high school for 17 years.
        I earned a BA in Music, a BA in Math Education, a graduate certification
        in secondary Math and science education from Central Washington University.
        I then continued my education earning an MBA with a concentration in international
        business from Portland State University where I studied abroad in China, and U.AE.,
        Qatar and Saudi Arabia.   I have worked in private schools, title 1 schools,
         alternative Ed, and mainstream public schools. I have served as a math coach, and
         first year teacher mentor.  I now serve as CEO of Ardor Education. While
         I no longer work in the classroom I believe that once a teacher always a teacher. 
        </p>

    - name: Chris Trevino
      title: Co-Founder & CTO
      image: 'assets/images/profile/chris.jpg'
      summary: >
        <p>
        I have been a professional software developer for over a decade. I earned my B.S in Computer Science at
        Washington State University (Go Cougs!), and my M.S. in Computer Science at Washington University in St. Louis.
        I have made software with a variety of software and organizational environments. I've worked in companies
        large and small, and projects ranging from F/A-18 Mission Control software to high-scale web services with
        millions of transactions a day.
        </p>
        <p>
        I love mathematics and the clarity it brings to understanding the world. Newton > Liebnitz. When I'm not making
        software, I enjoy cycling, homebrewing, playing guitar, and board-gaming.
        </p>

    - name: Isaac Flemming
      title: Co-Founder & Senior Software Engineer
      image: 'assets/images/profile/isaac.jpg'
      summary: >
        <p>
        Formally educated in Computer Science I have been an IT professional for over a decade. In this field I am
        challenged daily to do things better and quicker and in order to do this I have to always be learning. That is
        one of the things I love the most about what I do, the chance to find out new and interesting things every day.
        As enjoyable as it is to learn new things though, I get the biggest reward out of helping others learn. Whether
        it is working with my mom to teach my son about gardening or volunteering to teach high school kids programming.
        Helping people learn new things and overcome difficulties is an extremely rewarding experience.
        </p>
        <p>
        Now that I am working with Ardor Education I feel like I am able to teach and learn with the rest of the world.
        I am very excited to be working on products that will help students learn and help teachers teach. Knowing I am
        part of a group that will change the world, and help change education for the better is as rewarding as it gets.
        </p>

company:
  name: Ardor Education

analytics:
  gaTrackingId: 'UA-53477428-3'

contact:
  email: contact@ardoreducation.com
  facebook: https://www.facebook.com/ardoreducation
  linkedIn: https://www.linkedin.com/company/ardor-education
  github: https://github.com/ardor-education
  twitter: https://twitter.com/ardoreducation
  googlePlus: https://plus.google.com/+Ardoreducation/

support:
  email: support@ardor.zendesk.com
  zendesk: https://ardor.zendesk.com

# Build settings
markdown: kramdown
